# Generated by Django 4.1.4 on 2023-02-15 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_orders_adress_alter_orders_expected_deliverydate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='adress',
            new_name='address',
        ),
    ]
