# Generated by Django 4.1.4 on 2023-02-16 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_adress_orders_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offers',
            name='dicount',
        ),
        migrations.AddField(
            model_name='offers',
            name='discount',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offers',
            name='end_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='offers',
            name='start_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='expected_deliverydate',
            field=models.DateField(default=datetime.date(2023, 2, 21)),
        ),
    ]
